### ISSUE TITLE
Could you provide more usage examples?

### ISSUE THREAD

**Issue by rakafo** [notti/fnfqueue#4]
I want to pass a subset of packets from nftables to python to decide verdict based on either source or dest ip, but I can't figure out how to get these attributes from the packet object. Is there some place I could refer for related documentation on how to use your library?

**Comment by notti** [comment]
The `packet` object is not the decoded network packet - it is a object that holds:
-  raw packet payload (starting with the IP-Header - so no hardware protocol like Ethernet)
- additional metadata not part of the payload (e.g., timestamp, hardware protocol number, ...)
- an internal identifier so we can tell the kernel on which packet we set the verdict

So basically to get source/destination IP you have to decode `packet.payload` with a packet decoding library (e.g., [dpkt](https://pypi.org/project/dpkt/), [scapy](https://scapy.net/)).
This step is shown in the example fnfqueue_add0 (using scapy):
https://github.com/notti/fnfqueue/blob/b8c19507e7b2d71c709f73da84023ab0dfc82096/examples/fnfqueue_add0.py#L20
In this example p contains the decoded packet (starting from the IP layer) after this line. So to check for the IP address you could do:
```python
import fnfqueue
from scapy.all import *

queue = 1

conn = fnfqueue.Connection()

try:
    q = conn.bind(queue)
    q.set_mode(0xffff, fnfqueue.COPY_PACKET)
except PermissionError:
    print("Access denied; Do I have root rights or the needed capabilities?")
    sys.exit(-1)

while True:
    try:
        for packet in conn:
            p = IP(packet.payload)
            if p.src == "192.168.0.1" and p.dst == "192.168.0.2":
                packet.accept()
            else:
                packet.drop()
    except fnfqueue.BufferOverflowException:
        print("buffer error")

conn.close()
```
This would only let packets going from 192.168.0.1 to 192.168.0.2 through.

Keep in mind:

- You MUST call one of `mangle`, `accept`, `drop`, `verdict` for _each_ packet!
- After you called one of those function don't use the packet any longer.
- You should try to be as fast as possible - or you might loose packets (and or cause delays in your network).
  - use e.g. dpkt instead of scapy - it is way faster, but also more complicated to use (e.g., it won't decode the IP address for you - which also helps with speed - it's better to compare raw IPs).
  - build the filter in a way that simplest checks come first.

Hope this is what you are looking for.

**Comment by rakafo** [comment]
Thank you for taking the time to write such a great explanation. It solved the questions I had, thus was able to get the functionality I wanted.
