### ISSUE TITLE
Packet.verdict can crash with UnboundLocalError due to race on Connection closing

### ISSUE THREAD

**Issue by alexzorin** [notti/fnfqueue#8]
Hi, awesome module!

I noticed that on occasion in my application, `Packet.verdict` can race if the underlying connection was closed (i.e. in another thread):

https://github.com/notti/fnfqueue/blob/b8c19507e7b2d71c709f73da84023ab0dfc82096/fnfqueue/__init__.py#L162-L167

    File "/root/certbot-standalone-nfq/certbot_standalone_nfq/auth.py", line 77, in drain_queue
      pkt_in.drop()
    File "/root/certbot-standalone-nfq/venv/lib/python3.10/site-packages/fnfqueue/__init__.py", line 141, in drop
      self.verdict(DROP, 0)
    File "/root/certbot-standalone-nfq/venv/lib/python3.10/site-packages/fnfqueue/__init__.py", line 166, in verdict
      if ret == -1:
    UnboundLocalError: local variable 'ret' referenced before assignment

I am not sure if `fnfqueue` is supposed to be thread-safe in this way, I took a similar strategy for closing the connection as is described in https://github.com/notti/fnfqueue/issues/2. 

From what I understand, the corrected behavior is that an `OSError` should be raised if `Packet.verdict` is called after the connection is closed, which would be just fine.

In theory I think this might raise a need to be able to perform a graceful queue shutdown: request a shutdown, have the library user drain the queue until it is empty, then close the underlying connection. But for now I'm happy to just sleep between disabling the nfqueue rule and closing the nfqueue connection.

**Comment by notti** [comment]
Hmm as far as I remember it should be fully threadsafe (however, there might be a race condition here with 162/163).
But the thing you are hitting here is more of a logic error (if `self._conn._conn` is indeed `None`, then ret won't exist...)

=> Will take a bit, since the whole infrastructure here is a bit outdated. Steps I will take:

- [x] Reformat source, add typings
- [x] Remove python2
- [x] Convert the travis stuff to github actions and automate deployment
- [x] Fix whats left over

**Comment by notti** [comment]
New version with fix rolled out.

**Comment by alexzorin** [comment]
Thank you!
